version: "3.7"

services:
  sample-server:
    image: 477120415291.dkr.ecr.ap-northeast-1.amazonaws.com/dev:php-nginx-server
    container_name: sample-server
    volumes:
      - .:/var/www/html/sample-app:delegated
      - ./docker/dev/server/nginx.conf:/etc/nginx/nginx.conf:cached #Proper nginx.conf file needs to be mounted
    ports:
      - "8200:80"
    working_dir: /var/www/html/sample-app

  sample-queue:
    image: 477120415291.dkr.ecr.ap-northeast-1.amazonaws.com/dev:queue-scheduler
    # command: php /var/www/html/sample-app/artisan horizon # For Horizon
    command: php /var/www/html/sample-app/artisan queue:listen --tries=3 --queue="sqs-queue-name" # For SQS
    container_name: sample-queue
    volumes:
      - .:/var/www/html/sample-app:delegated

  sample-scheduler:
    image: 477120415291.dkr.ecr.ap-northeast-1.amazonaws.com/dev:queue-scheduler
    entrypoint:
      [
        "sh",
        "-c",
        "while true; do php /var/www/html/sample-app/artisan schedule:run --verbose --no-interaction & sleep 60; done",
      ]
    container_name: sample-scheduler
    volumes:
      - .:/var/www/html/sample-app:delegated
