version: "3.7"

# networks:
#   default:
#     external:
#       name: dev

services:
  sample-php:
    image: 477120415291.dkr.ecr.ap-northeast-1.amazonaws.com/dev:php
    container_name: sample-php
    volumes:
      - .:/var/www/html/sample-app:delegated
    working_dir: /var/www/html/sample-app
    depends_on:
      - sample-mysql

  # Open http://localhost:8100/sample-app for prod to see result of npm run build.
  # That is after running npm run build on local device
  sample-nginx:
    image: nginx:stable-alpine
    container_name: sample-nginx
    ports:
      - "8100:80"
    volumes:
      - .:/var/www/html/sample-app
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:cached # Make sure the file exists in the correct directory
    depends_on:
      - sample-php
      - sample-mysql

  sample-queue:
    image: 477120415291.dkr.ecr.ap-northeast-1.amazonaws.com/dev:php
    # command: php /var/www/html/sample-app/artisan horizon # For Horizon
    command: php /var/www/html/sample-app/artisan queue:listen --tries=3 --queue="sqs-queue-name" # For SQS
    container_name: sample-queue
    volumes:
      - .:/var/www/html/sample-app:delegated

  sample-scheduler:
    image: 477120415291.dkr.ecr.ap-northeast-1.amazonaws.com/dev:php
    entrypoint:
      [
        "sh",
        "-c",
        "while true; do php /var/www/html/sample-app/artisan schedule:run --verbose --no-interaction & sleep 60; done",
      ]
    container_name: sample-scheduler
    volumes:
      - .:/var/www/html/sample-app:delegated
